# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8f9119cb3366c663c856b941bb5408a7b9db9b763b5ce2e797e5f6e5fc5900637b5e5c0e05d55389719f63dbe20678900bd586f72047476455944a3462f3e91

test:
  secret_key_base: 88a9e23580fff684d92bfaa38a507e641f9d35336fa87298038f04e1c182801180f8f2434e4ddcbcda077f8b85634f3f0096d82107f71b9f217ccdf547857324

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
